//Home Page constants
export const CREATE_EXPENSE = 'CREATE_EXPENSE';
export const CREATE_BUDGET = 'CREATE_BUDGET';
export const CREATE_INCOME = 'CREATE_INCOME';
export const CREATE_INCOMECAT = 'CREATE_INCOMECAT';
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
export const UPDATE_BUDGET = 'UPDATE_BUDGET';
export const UPDATE_INCOME = 'UPDATE_INCOME';
export const UPDATE_INCOMECAT = 'UPDATE_INCOMECAT';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const DELETE_BUDGET = 'DELETE_BUDGET';
export const DELETE_INCOME = 'DELETE_INCOME';
export const DELETE_INCOMECAT = 'DELETE_INCOMECAT';
export const FETCH_EXPENSES = 'FETCH_EXPENSES';
export const FETCH_INCOMES = 'FETCH_INCOMES';
export const FETCH_BUDGETS = 'FETCH_BUDGETS';
export const FETCH_INCOMECATS = 'FETCH_INCOMECATS';

//Accounts Page constants
export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const FETCH_ACCOUNTNAMES = 'FETCH_ACCOUNTNAMES';
export const CREATE_ACCOUNTNAME = 'CREATE_ACCOUNTNAME';
export const UPDATE_ACCOUNTNAME = 'UPDATE_ACCOUNTNAME';
export const DELETE_ACCOUNTNAME = 'DELETE_ACCOUNTNAME';

//Auth Page constants
export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';